// Central permission names keep role access explicit and ready for database-backed permissions later.
import { UserRole } from "@prisma/client";

export const OPERATION_PERMISSIONS = {
  DASHBOARD_VIEW: "operations.dashboard.view",
  EMPLOYEES_VIEW: "operations.employees.view",
  EMPLOYEES_CREATE: "operations.employees.create",
  EMPLOYEES_UPDATE: "operations.employees.update",
  EMPLOYEES_DELETE: "operations.employees.delete",
  CUSTOMERS_VIEW: "operations.customers.view",
  BOOKINGS_VIEW: "operations.bookings.view",
  BOOKINGS_CREATE: "operations.bookings.create",
  BOOKINGS_UPDATE: "operations.bookings.update",
  BOOKINGS_CANCEL: "operations.bookings.cancel",
  ORDERS_VIEW: "operations.orders.view",
  ORDERS_UPDATE: "operations.orders.update",
  MENU_VIEW: "operations.menu.view",
  MENU_CREATE: "operations.menu.create",
  MENU_UPDATE: "operations.menu.update",
  MENU_DELETE: "operations.menu.delete",
  CATEGORIES_VIEW: "operations.categories.view",
  CATEGORIES_CREATE: "operations.categories.create",
  CATEGORIES_UPDATE: "operations.categories.update",
  CATEGORIES_DELETE: "operations.categories.delete",
  TABLES_VIEW: "operations.tables.view",
  TABLES_CREATE: "operations.tables.create",
  TABLES_UPDATE: "operations.tables.update",
  TABLES_DELETE: "operations.tables.delete",
  FLOORS_VIEW: "operations.floors.view",
  FLOORS_CREATE: "operations.floors.create",
  FLOORS_UPDATE: "operations.floors.update",
  FLOORS_DELETE: "operations.floors.delete",
  ROOMS_VIEW: "operations.rooms.view",
  ROOMS_CREATE: "operations.rooms.create",
  ROOMS_UPDATE: "operations.rooms.update",
  ROOMS_DELETE: "operations.rooms.delete",
  OFFERS_VIEW: "operations.offers.view",
  OFFERS_CREATE: "operations.offers.create",
  OFFERS_UPDATE: "operations.offers.update",
  OFFERS_DELETE: "operations.offers.delete",
  REPORTS_VIEW: "operations.reports.view",
  NOTIFICATIONS_VIEW: "operations.notifications.view",
  RECEPTION_VIEW: "operations.reception.view",
  KITCHEN_VIEW: "operations.kitchen.view",
  MANAGER_VIEW: "operations.manager.view",
  ADMIN_VIEW: "operations.admin.view",
  PAYMENTS_VIEW: "operations.payments.view",
  SETTINGS_VIEW: "operations.settings.view",
  SETTINGS_UPDATE: "operations.settings.update",
  ROLES_VIEW: "operations.roles.view",
  PERMISSIONS_MANAGE: "operations.permissions.manage",
  AUDIT_LOGS_VIEW: "operations.audit-logs.view",
} as const;

export type OperationPermission = (typeof OPERATION_PERMISSIONS)[keyof typeof OPERATION_PERMISSIONS];

export const ROLE_PERMISSION_MAP: Record<UserRole, OperationPermission[]> = {
  CUSTOMER: [],
  RECEPTION: [
    OPERATION_PERMISSIONS.DASHBOARD_VIEW,
    OPERATION_PERMISSIONS.RECEPTION_VIEW,
    OPERATION_PERMISSIONS.CUSTOMERS_VIEW,
    OPERATION_PERMISSIONS.BOOKINGS_VIEW,
    OPERATION_PERMISSIONS.BOOKINGS_CREATE,
    OPERATION_PERMISSIONS.BOOKINGS_UPDATE,
    OPERATION_PERMISSIONS.ORDERS_VIEW,
    OPERATION_PERMISSIONS.PAYMENTS_VIEW,
    OPERATION_PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  KITCHEN: [
    OPERATION_PERMISSIONS.DASHBOARD_VIEW,
    OPERATION_PERMISSIONS.KITCHEN_VIEW,
    OPERATION_PERMISSIONS.ORDERS_VIEW,
    OPERATION_PERMISSIONS.ORDERS_UPDATE,
    OPERATION_PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  MANAGER: [
    OPERATION_PERMISSIONS.DASHBOARD_VIEW,
    OPERATION_PERMISSIONS.RECEPTION_VIEW,
    OPERATION_PERMISSIONS.KITCHEN_VIEW,
    OPERATION_PERMISSIONS.MANAGER_VIEW,
    OPERATION_PERMISSIONS.CUSTOMERS_VIEW,
    OPERATION_PERMISSIONS.BOOKINGS_VIEW,
    OPERATION_PERMISSIONS.BOOKINGS_CREATE,
    OPERATION_PERMISSIONS.BOOKINGS_UPDATE,
    OPERATION_PERMISSIONS.BOOKINGS_CANCEL,
    OPERATION_PERMISSIONS.ORDERS_VIEW,
    OPERATION_PERMISSIONS.ORDERS_UPDATE,
    OPERATION_PERMISSIONS.MENU_VIEW,
    OPERATION_PERMISSIONS.MENU_CREATE,
    OPERATION_PERMISSIONS.MENU_UPDATE,
    OPERATION_PERMISSIONS.CATEGORIES_VIEW,
    OPERATION_PERMISSIONS.CATEGORIES_CREATE,
    OPERATION_PERMISSIONS.CATEGORIES_UPDATE,
    OPERATION_PERMISSIONS.TABLES_VIEW,
    OPERATION_PERMISSIONS.TABLES_CREATE,
    OPERATION_PERMISSIONS.TABLES_UPDATE,
    OPERATION_PERMISSIONS.FLOORS_VIEW,
    OPERATION_PERMISSIONS.FLOORS_CREATE,
    OPERATION_PERMISSIONS.FLOORS_UPDATE,
    OPERATION_PERMISSIONS.ROOMS_VIEW,
    OPERATION_PERMISSIONS.ROOMS_CREATE,
    OPERATION_PERMISSIONS.ROOMS_UPDATE,
    OPERATION_PERMISSIONS.OFFERS_VIEW,
    OPERATION_PERMISSIONS.OFFERS_CREATE,
    OPERATION_PERMISSIONS.OFFERS_UPDATE,
    OPERATION_PERMISSIONS.REPORTS_VIEW,
    OPERATION_PERMISSIONS.PAYMENTS_VIEW,
    OPERATION_PERMISSIONS.NOTIFICATIONS_VIEW,
    OPERATION_PERMISSIONS.SETTINGS_VIEW,
  ],
  ADMIN: Object.values(OPERATION_PERMISSIONS),
};
