// Centralizes application-wide constants shared by future modules.
export const APP_NAME = "SAFNAM Restaurant";

export const USER_ROLES = {
  CUSTOMER: "CUSTOMER",
  RECEPTION: "RECEPTION",
  KITCHEN: "KITCHEN",
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
} as const;

export const USER_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  BLOCKED: "BLOCKED",
} as const;

export const BOOKING_STATUSES = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CHECKED_IN: "CHECKED_IN",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
} as const;

export const BOOKING_TYPES = {
  TABLE: "TABLE",
  ROOM: "ROOM",
} as const;

export const BOOKING_SOURCES = {
  CUSTOMER_APP: "CUSTOMER_APP",
  RECEPTION: "RECEPTION",
  ADMIN: "ADMIN",
} as const;

export const ORDER_STATUSES = {
  DRAFT: "DRAFT",
  PLACED: "PLACED",
  PREPARING: "PREPARING",
  READY: "READY",
  SERVED: "SERVED",
  CANCELLED: "CANCELLED",
} as const;

export const PAYMENT_STATUSES = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
} as const;

export const TABLE_STATUSES = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  OCCUPIED: "OCCUPIED",
  BILLING: "BILLING",
  CLEANING: "CLEANING",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
} as const;

export const ROOM_STATUSES = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  OCCUPIED: "OCCUPIED",
  CLEANING: "CLEANING",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
} as const;

export const FLOOR_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export const TABLE_SHAPES = {
  SQUARE: "SQUARE",
  RECTANGLE: "RECTANGLE",
  ROUND: "ROUND",
  OVAL: "OVAL",
} as const;
